repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: debug-statements
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/reorder_python_imports
    hooks:
      - id: reorder-python-imports
        args: [--application-directories, ".:src", --py36-plus]
  - repo: https://github.com/psf/black
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
  - repo: https://gitlab.com/pycqa/flake8
    hooks:
      - id: flake8
  - repo: https://githubcom/pre-commit/mirrors-isort
    hooks:
      - id: isort
